image: node:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .yarn
    - .next
  policy: pull-push

stages:
  - install
  - lint
  - preview

install:
  stage: install
  script:
    - yarn install --immutable
  artifacts:
    paths:
      - .yarn
      - node_modules
    expire_in: 1 hour  # Можно увеличить срок хранения
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always

lint:
  stage: lint
  script:
    - yarn lint
  dependencies:
    - install
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success

preview:
  stage: preview
  script:
    - |
      curl \
        --data-urlencode "body=## After build preview will 🚀[be here!](https://pr-${CI_MERGE_REQUEST_IID}.${AMPLIFY_APP_ID}.amplifyapp.com/)" \
        --request POST \
        --header "PRIVATE-TOKEN: ${GITLAB_ACCESS_TOKEN}" \
        "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/merge_requests/${CI_MERGE_REQUEST_IID}/notes"
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"'
      when: on_success
    - when: never
